### ISSUE TITLE
Maki outputs an incorrect definition location range for macros using line continuation

### ISSUE THREAD

**Issue by SilverMight** [appleseedlab/maki#69]
Given a source file containing a macro definition utilization a line continuation character like this:

```c
#define STRING_LITERAL \
"String literal"

int main() {
	char * a = STRING_LITERAL;
}
```

Maki will output a definition like this:
```
  {
    "Kind": "Definition",
    "Name": "STRING_LITERAL",
    "IsObjectLike": true,
    "IsDefinitionLocationValid": true,
    "Body": "\"String literal\"",
    "IsDefinedAtGlobalScope": true,
    "DefinitionLocation": "/home/silvermight/maki/newlinefail.c:1:9",
    "EndDefinitionLocation": "/home/silvermight/maki/newlinefail.c:1:24"
  },
```
With the `EndDefinitionLocation` ending at the line continuation character, and not the actual end of the macro (the end of the string literal on the next line).

This causes issues translating some codebases that use this heavily, i.e SQLite3 and Python.

**Comment by PappasBrent** [comment]
I'm looking into this now, but if this turns out to be an issue with Clang then we could fix this with MerC by just checking if the EndDefinitionLocation points to a backslash-newline, and if so, then just adding the next line to the macro definition.
